<div align="center">

# PYTHON · MÓDULO 3
## Pandas + NumPy · Análisis de Datos

**Autor:** Borja Mora Méndez · **Nivel:** Intermedio · **Objetivo:** Data Analyst / BI / Power BI

</div>

---

### ¿De qué trata este archivo?

Aquí empieza lo que de verdad vas a hacer como analista: **manejar tablas de datos con Pandas**.
Si Power BI y SQL son tu mundo, Pandas es ese mismo mundo pero **en código**: cargar datos,
limpiarlos, filtrarlos, agruparlos y sacar conclusiones.

> Idea base: un **DataFrame** es una **tabla de Excel** dentro de Python. Filas, columnas y
> un montón de "botones" (métodos) para transformarla. Y recuerda del Módulo 2: ese DataFrame
> **es un objeto**, así que todo lo que hagas (`df.head()`, `df.groupby()`) son **métodos** suyos.

---

### Hoja de ruta — ¿dónde estás?

```
[x] MÓDULO 1 - Fundamentos
[x] MÓDULO 2 - Programación Orientada a Objetos (POO)
[>] MÓDULO 3 - Pandas + NumPy                          ← ESTÁS AQUÍ
[ ] MÓDULO 4 - Visualización (Matplotlib / Seaborn)
[ ] MÓDULO 5 - Polars + DuckDB
[ ] MÓDULO 6 - Python para Power BI / SQL Server
[ ] MÓDULO 7 - Buenas prácticas profesionales
```

### Índice del Módulo 3
| Parte | Tema |
|-------|------|
| **A — Teoría Pandas** | Series y DataFrame · cargar CSV · `head/tail/info/describe` · limpieza de nulos · columnas y filtros · estadística · `groupby` · `iloc/loc` |
| **B — Proyecto `ventas_500`** | EDA completo · limpieza por criterios · preguntas de negocio · columnas derivadas · percentiles · correlación |

> Tabla de partida en varios ejemplos: `ventas_500.csv` (empleados, ventas, clientes).

---

# PARTE A · Teoría de Pandas

## 1. `Series` y `DataFrame` — las dos piezas base

**Qué es:** las dos estructuras de datos base de Pandas — todo lo demás se construye sobre ellas.

### Analogía sencilla

- Una **`Series`** es **una sola columna** (una lista con etiquetas).
- Un **`DataFrame`** es **la tabla entera** (muchas columnas juntas).

```
   Series            DataFrame
   ┌────┐        ┌────────┬──────┐
   │ 10 │        │ Nombre │ Edad │
   │ 20 │        ├────────┼──────┤
   │ 30 │        │ Ana    │  23  │
   └────┘        │ Luis   │  35  │
                 │ Marta  │  29  │
                 └────────┴──────┘
```

### Aplicación profesional

El DataFrame es tu **tabla de SQL Server** o tu **tabla de Power Query**. La Series
es **una columna** de esa tabla. `import pandas as pd` es el "abrir el programa".

In [1]:
import pandas as pd

In [2]:
serie = pd.Series([10,20,30])

df = pd.DataFrame({
 "Nombre":["Ana", "Luis", "Marta"],
 "Edad": [23,35,29]
})

In [3]:
print(serie)

0    10
1    20
2    30
dtype: int64

In [4]:
print(df)

  Nombre  Edad
0    Ana    23
1   Luis    35
2  Marta    29

In [5]:
display(df)

  Nombre  Edad
0    Ana    23
1   Luis    35
2  Marta    29

## 2. Cargar ficheros externos · `read_csv`

**Qué es:** la función que convierte un archivo externo en un DataFrame — normalmente el primer paso real de cualquier análisis.

### Aplicación profesional

Es el **"Obtener datos → CSV"** de Power BI, pero en una línea. `pd.read_csv(ruta)` lee el
archivo y lo convierte en DataFrame.

### Error común

Olvidar la `r` antes de la ruta (`r"C:\..."`). Esa `r` la marca como *raw string*: evita que las barras `\`
se interpreten como caracteres especiales. Imprescindible en rutas de Windows.

In [6]:
dp=pd.read_csv(r"ventas_empleados.csv")
display(dp)

     nombre  edad departamento  ventas  clientes
0     Sofia  49.0       Ventas  2763.0      52.0
1    Carlos  36.0       Ventas   502.0       NaN
2     Jorge  39.0    Marketing   659.0      32.0
3     Lucia  44.0    Marketing  1280.0      89.0
4     Sofia  41.0      Soporte  1392.0      56.0
..      ...   ...          ...     ...       ...
495     Ana  42.0      Soporte  1443.0      55.0
496   Sofia  45.0       Ventas  2890.0      16.0
497   Sofia  31.0       Ventas  1849.0      32.0
498   Elena  45.0       Ventas  2911.0      84.0
499   Marta  32.0    Marketing  1390.0      95.0

[500 rows x 5 columns]

## 3. Primeros pasos · conocer la tabla (EDA)

Antes de analizar, **miras** los datos. Estas 4 herramientas son tu primer vistazo:

| Método | Qué hace | Equivalente mental |
|--------|----------|--------------------|
| `.head(n)` | primeras n filas | asomarte por arriba |
| `.tail(n)` | últimas n filas | asomarte por abajo |
| `.info()` | tipos y nulos por columna | la "ficha técnica" |
| `.describe()` | estadísticas (media, min, max…) | resumen numérico |

**EDA = Exploratory Data Analysis.** Es lo primero que hace cualquier analista con una tabla nueva.

In [7]:
## Visualización de los primeros casos

dp.head(10)

   nombre  edad departamento  ventas  clientes
0   Sofia  49.0       Ventas  2763.0      52.0
1  Carlos  36.0       Ventas   502.0       NaN
2   Jorge  39.0    Marketing   659.0      32.0
3   Lucia  44.0    Marketing  1280.0      89.0
4   Sofia  41.0      Soporte  1392.0      56.0
5    Raul  32.0      Soporte  2530.0      24.0
6   Marta  38.0    Marketing  2876.0      34.0
7   Sofia  55.0    Marketing  1079.0      45.0
8   Jorge  31.0      Soporte  2433.0      84.0
9   Lucia  38.0       Ventas  1880.0      60.0

In [8]:
## Visualización de los últimos casos

dp.tail(10)

    nombre  edad departamento  ventas  clientes
490    Ana   NaN       Ventas   511.0      27.0
491  Sofia  59.0    Marketing  1656.0      30.0
492  Jorge  57.0    Marketing   803.0       NaN
493  Sofia  25.0      Soporte  2263.0      30.0
494  Lucia  27.0       Ventas   542.0      17.0
495    Ana  42.0      Soporte  1443.0      55.0
496  Sofia  45.0       Ventas  2890.0      16.0
497  Sofia  31.0       Ventas  1849.0      32.0
498  Elena  45.0       Ventas  2911.0      84.0
499  Marta  32.0    Marketing  1390.0      95.0

In [9]:
## Información

dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nombre        500 non-null    object
 1   edad          490 non-null    float64
 2   departamento  500 non-null    object
 3   ventas        490 non-null    float64
 4   clientes      490 non-null    float64
dtypes: float64(3), object(2)
memory usage: 19.7+ KB

In [10]:
## Análisis exploratorio

print(dp.describe())

             edad       ventas    clientes
count  490.000000   490.000000  490.000000
mean    39.497959  1757.226531   51.238776
std     11.735017   716.355563   26.136697
min     20.000000   501.000000   10.000000
25%     29.000000  1166.500000   29.250000
50%     40.000000  1756.000000   48.000000
75%     50.000000  2431.500000   74.000000
max     59.000000  2977.000000   99.000000

## 4. Limpieza de datos · valores nulos (`NaN`)

**Qué es:** decidir qué hacer con las casillas vacías de la tabla antes de calcular nada con ellas.

### Analogía sencilla

Un `NaN` es una **casilla vacía** en la tabla. Antes de hacer
cuentas hay que decidir qué hacer con los huecos: **contarlos**, **borrar** esas filas, o **rellenarlos**.

```
   .isnull().sum()  →  ¿cuántos huecos hay por columna?
   .dropna()        →  BORRA las filas con huecos
   .fillna(valor)   →  RELLENA los huecos con un valor
```

### Aplicación profesional

Es exactamente "Quitar filas con errores" o "Reemplazar valores" de Power Query.
La decisión (borrar vs rellenar) es una de las más importantes del análisis.

In [11]:
import numpy as np

df = pd.DataFrame({ "Nombre": ["Ana", "Luis", "Pedro", "Marta", "Juan"], "Edad": [23, np.nan, 35, 28, np.nan], "Ciudad": ["Madrid", "Barcelona", np.nan, "Valencia", "Sevilla"], "Ventas": [200, 150, np.nan, 300, 250] })


display(df)

  Nombre  Edad     Ciudad  Ventas
0    Ana  23.0     Madrid   200.0
1   Luis   NaN  Barcelona   150.0
2  Pedro  35.0        NaN     NaN
3  Marta  28.0   Valencia   300.0
4   Juan   NaN    Sevilla   250.0

In [12]:
## Contar el numero de valores nulos para cada columna

df.isnull().sum()

Nombre    0
Edad      2
Ciudad    1
Ventas    1
dtype: int64

In [13]:
## Eliminar filas que contengan un valor nulo

df_sin_nulos = df.dropna()
display(df_sin_nulos)

  Nombre  Edad    Ciudad  Ventas
0    Ana  23.0    Madrid   200.0
3  Marta  28.0  Valencia   300.0

In [14]:
## Rellenar los nulos por ceros

df_relleno = df.fillna(0)
display(df_relleno)
display(df)

  Nombre  Edad     Ciudad  Ventas
0    Ana  23.0     Madrid   200.0
1   Luis   0.0  Barcelona   150.0
2  Pedro  35.0          0     0.0
3  Marta  28.0   Valencia   300.0
4   Juan   0.0    Sevilla   250.0

  Nombre  Edad     Ciudad  Ventas
0    Ana  23.0     Madrid   200.0
1   Luis   NaN  Barcelona   150.0
2  Pedro  35.0        NaN     NaN
3  Marta  28.0   Valencia   300.0
4   Juan   NaN    Sevilla   250.0

## 5. Crear columnas nuevas y filtrar filas

**Qué es:** las dos operaciones que más vas a repetir en cualquier análisis: derivar una columna a partir de otras, y quedarte solo con las filas que cumplen una condición.

**Columna nueva:** `df["Ingresos"] = df["Unidades"] * df["Precio"]`. Es como una **columna
calculada** de Power BI/DAX, pero operando sobre toda la columna de golpe (*vectorizado*).

**Filtrar:** `df[df["Producto"] == "Laptop"]` se lee de dentro afuera: primero la condición
(devuelve True/False por fila), y el DataFrame se queda **solo con las filas True**.

```
   df[ df["Unidades"] > 4 ]
        └── máscara de True/False ──┘
        →  solo pasan las filas donde es True
```

### Aplicación profesional

La columna nueva es una *calculated column*; el filtro es el `WHERE` de SQL o el
filtro de un visual en Power BI.

In [15]:
## Nuevo dataframe

df = pd.DataFrame({"Fecha": pd.to_datetime(["2025-01-01","2025-01-02","2025-01-03","2025-01-04","2025-01-05"]),
 "Producto": ["Laptop","Tablet","Smartphone","Laptop","Tablet"],
 "Unidades": [5, np.nan, 8, 3, 6],
 "Precio": [800, 300, np.nan, 820, 310] })

In [16]:
## Crear una columna nueva

df["Ingresos"] = df["Unidades"] * df["Precio"]
display(df)

       Fecha    Producto  Unidades  Precio  Ingresos
0 2025-01-01      Laptop       5.0   800.0    4000.0
1 2025-01-02      Tablet       NaN   300.0       NaN
2 2025-01-03  Smartphone       8.0     NaN       NaN
3 2025-01-04      Laptop       3.0   820.0    2460.0
4 2025-01-05      Tablet       6.0   310.0    1860.0

In [17]:
## Filtrado de datos

df[df["Producto"] == "Laptop"]

       Fecha Producto  Unidades  Precio  Ingresos
0 2025-01-01   Laptop       5.0   800.0    4000.0
3 2025-01-04   Laptop       3.0   820.0    2460.0

In [18]:
df[df["Unidades"] > 4]

       Fecha    Producto  Unidades  Precio  Ingresos
0 2025-01-01      Laptop       5.0   800.0    4000.0
2 2025-01-03  Smartphone       8.0     NaN       NaN
4 2025-01-05      Tablet       6.0   310.0    1860.0

## 6. Estadística básica y ordenación

**Qué es:** aplicar una cuenta a toda una columna, y ordenar la tabla por el resultado.

`.mean()`, `.max()`… aplican una cuenta a **toda una columna**. Y un truco muy útil:
**rellenar los huecos con la media** de la propia columna (`fillna(df["x"].mean())`), para no
perder filas pero tampoco inventar.

`.sort_values(by="Ingresos", ascending=False)` = **ordenar de mayor a menor**, como pinchar la
cabecera de una columna en Excel.

### Aplicación profesional

`.mean()` = `AVG()` en SQL / `AVERAGE()` en DAX. `.sort_values()` = `ORDER BY`.

In [19]:
df["Unidades"].mean()

np.float64(5.5)

In [20]:
df["Unidades"].max()

np.float64(8.0)

In [21]:
#€ Rellenar nulos con la media

df["Unidades"] = df["Unidades"].fillna(df["Unidades"].mean())
df["Precio"] = df["Precio"].fillna(df["Precio"].mean())

print(df)

       Fecha    Producto  Unidades  Precio  Ingresos
0 2025-01-01      Laptop       5.0   800.0    4000.0
1 2025-01-02      Tablet       5.5   300.0       NaN
2 2025-01-03  Smartphone       8.0   557.5       NaN
3 2025-01-04      Laptop       3.0   820.0    2460.0
4 2025-01-05      Tablet       6.0   310.0    1860.0

In [22]:
df.sort_values(by="Ingresos", ascending=False)

       Fecha    Producto  Unidades  Precio  Ingresos
0 2025-01-01      Laptop       5.0   800.0    4000.0
3 2025-01-04      Laptop       3.0   820.0    2460.0
4 2025-01-05      Tablet       6.0   310.0    1860.0
1 2025-01-02      Tablet       5.5   300.0       NaN
2 2025-01-03  Smartphone       8.0   557.5       NaN

## 7. Agrupaciones · `groupby` (el corazón del análisis)

**Qué es:** la operación más usada en cualquier análisis de negocio — juntar filas que comparten algo y sacar un número por grupo.

### Analogía sencilla

`groupby` es **hacer montones**. Juntas las filas que comparten
algo (ej. el mismo producto) y sacas un número por montón (la suma, la media…).

```
   df.groupby("Producto")["Ingresos"].sum()
        │                    │          └── ¿qué cuenta? → la suma
        │                    └── ¿de qué columna?
        └── ¿por qué agrupamos?
```

### Aplicación profesional

Es el `GROUP BY` de SQL, o lo que hace una **matriz/tabla dinámica**
en Power BI al arrastrar una dimensión y una medida. Si dominas esto, dominas Pandas.

In [23]:
## Ingresos por producto


df.groupby("Producto")["Ingresos"].sum()

Producto
Laptop        6460.0
Smartphone       0.0
Tablet        1860.0
Name: Ingresos, dtype: float64

In [24]:
## Promedio de precio por producto


promedio_precio_por_producto = df.groupby("Producto")["Precio"].mean()
print(promedio_precio_por_producto)

Producto
Laptop        810.0
Smartphone    557.5
Tablet        305.0
Name: Precio, dtype: float64

## 8. Acceder a filas concretas · `iloc` y `loc`

**Qué es:** dos formas complementarias de señalar filas concretas de una tabla.

- **`.iloc[n]`** → por **posición** (el número de asiento, empieza en 0). *i = index numérico.*
- **`.loc[etiqueta]`** → por **etiqueta/condición** (por nombre o por una regla).

Un combo precioso: `df.loc[df["Ingresos"].idxmax()]` → `idxmax()` te da la **posición del valor
máximo**, y `.loc[...]` trae esa fila entera. Es "dame la fila del campeón".

### Aplicación profesional

`iloc` es "la fila número N"; `loc` con condición es como un `WHERE` que devuelve
el registro top. `idxmax()` ≈ `TOPN(1, ...)` en DAX.

---

### Ejercicio — Tu fila favorita

Sobre el `df` de productos que acabas de usar, calcula `df.loc[df["Precio"].idxmax()]`
para encontrar el producto más caro, y compáralo con `df.iloc[0]` (el primero por
posición, no por valor). Comprueba que no tienen por qué coincidir.

In [25]:
display(df)

       Fecha    Producto  Unidades  Precio  Ingresos
0 2025-01-01      Laptop       5.0   800.0    4000.0
1 2025-01-02      Tablet       5.5   300.0       NaN
2 2025-01-03  Smartphone       8.0   557.5       NaN
3 2025-01-04      Laptop       3.0   820.0    2460.0
4 2025-01-05      Tablet       6.0   310.0    1860.0

In [26]:
df.iloc[4]

Fecha       2025-01-05 00:00:00
Producto                 Tablet
Unidades                    6.0
Precio                    310.0
Ingresos                 1860.0
Name: 4, dtype: object

In [27]:
df.iloc[1:4]

       Fecha    Producto  Unidades  Precio  Ingresos
1 2025-01-02      Tablet       5.5   300.0       NaN
2 2025-01-03  Smartphone       8.0   557.5       NaN
3 2025-01-04      Laptop       3.0   820.0    2460.0

In [28]:
## Te devuelve el máximo de la columna que le metamos
df.loc[df["Ingresos"].idxmax()]

Fecha       2025-01-01 00:00:00
Producto                 Laptop
Unidades                    5.0
Precio                    800.0
Ingresos                 4000.0
Name: 0, dtype: object

---
# PARTE B · Proyecto real · `ventas_500`

Ahora aplicas **todo lo anterior** a un caso de empresa: ventas de empleados por departamento.
Este es el tipo de mini-proyecto que enseñarías en una entrevista de Data Analyst.

**Flujo profesional que vas a seguir:**
```
   Cargar  →  Explorar (EDA)  →  Limpiar  →  Responder preguntas de negocio  →  Correlación
```

## B.1 · Planteamiento e importación
El comentario inicial define el **objetivo de negocio** (buena costumbre: documentar antes de codear).

In [29]:
# De ventas de los empleados de una empresa

# Se dispone de un fichero con información de:


#Nombre del empleado
#Edad
#Departamento
#Ventas mensuales
#Numero de clientes atendidos


#Objetivo


# Cargar los datos en Python
# Limpiar datos incorrectos o vacios
# Analizar estadisticas básicas
# Realizar cálculos con NumPy
# Realizar preguntas sobre el negocio

In [30]:
#PASO 1 - Importar librerias

import pandas as pd
import numpy as np

In [31]:
#PASO2 - Cargar archivo

dp=pd.read_csv(r"ventas_empleados.csv")
display(dp)

     nombre  edad departamento  ventas  clientes
0     Sofia  49.0       Ventas  2763.0      52.0
1    Carlos  36.0       Ventas   502.0       NaN
2     Jorge  39.0    Marketing   659.0      32.0
3     Lucia  44.0    Marketing  1280.0      89.0
4     Sofia  41.0      Soporte  1392.0      56.0
..      ...   ...          ...     ...       ...
495     Ana  42.0      Soporte  1443.0      55.0
496   Sofia  45.0       Ventas  2890.0      16.0
497   Sofia  31.0       Ventas  1849.0      32.0
498   Elena  45.0       Ventas  2911.0      84.0
499   Marta  32.0    Marketing  1390.0      95.0

[500 rows x 5 columns]

## B.2 · EDA — radiografía del dataset
Aquí brillan dos cálculos muy "de informe": el **total de nulos** de un vistazo
(`.isna().sum().sum()` — doble suma: por columna y luego total) y el **% de nulos por columna**,
que es justo lo que pondrías en un informe de calidad de datos.

In [32]:
#PASO 3 - EDA

dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   nombre        500 non-null    object
 1   edad          490 non-null    float64
 2   departamento  500 non-null    object
 3   ventas        490 non-null    float64
 4   clientes      490 non-null    float64
dtypes: float64(3), object(2)
memory usage: 19.7+ KB

In [33]:
# Total de nulos en TODO el dataset, un solo número
dp.isna().sum().sum()

np.int64(30)

In [34]:
# Porcentaje de nulos por columna (muy útil en informes)
(dp.isna().sum() / len(dp) * 100).round(2)

nombre          0.0
edad            2.0
departamento    0.0
ventas          2.0
clientes        2.0
dtype: float64

In [35]:
dp.describe()

             edad       ventas    clientes
count  490.000000   490.000000  490.000000
mean    39.497959  1757.226531   51.238776
std     11.735017   716.355563   26.136697
min     20.000000   501.000000   10.000000
25%     29.000000  1166.500000   29.250000
50%     40.000000  1756.000000   48.000000
75%     50.000000  2431.500000   74.000000
max     59.000000  2977.000000   99.000000

## B.3 · Limpieza (opción A): eliminar filas con nulos

`dropna()` crea una versión sin huecos. Comparas el `describe()` del original con el limpio para
ver **cuánto cambia** al borrar.

### Error común

En los `print("\ Archivo limpio", ...)` de abajo, esa `\ ` es una secuencia de escape
rara (probablemente se quería `\n`, salto de línea). Funciona igualmente porque `\ ` no es una
secuencia reconocida y Python la deja tal cual, pero conviene no repetir el error: para saltar de
línea dentro de un `print`, usa `\n`.

In [36]:
#PASO 4 - Limpieza de datos

#Eliminar filas con valores nulos


dp_limpio =dp.dropna()
display(dp_limpio)
dp_limpio.describe()

    nombre  edad departamento  ventas  clientes
0    Sofia  49.0       Ventas  2763.0      52.0
2    Jorge  39.0    Marketing   659.0      32.0
3    Lucia  44.0    Marketing  1280.0      89.0
4    Sofia  41.0      Soporte  1392.0      56.0
5     Raul  32.0      Soporte  2530.0      24.0
..     ...   ...          ...     ...       ...
495    Ana  42.0      Soporte  1443.0      55.0
496  Sofia  45.0       Ventas  2890.0      16.0
497  Sofia  31.0       Ventas  1849.0      32.0
498  Elena  45.0       Ventas  2911.0      84.0
499  Marta  32.0    Marketing  1390.0      95.0

[471 rows x 5 columns]

             edad       ventas    clientes
count  471.000000   471.000000  471.000000
mean    39.505308  1763.360934   51.668790
std     11.789983   710.263967   26.201037
min     20.000000   501.000000   10.000000
25%     29.000000  1185.000000   30.000000
50%     40.000000  1766.000000   48.000000
75%     50.000000  2430.000000   75.000000
max     59.000000  2974.000000   99.000000

In [37]:
print("\ Archivo limpio",
 dp.describe())

\ Archivo limpio              edad       ventas    clientes
count  490.000000   490.000000  490.000000
mean    39.497959  1757.226531   51.238776
std     11.735017   716.355563   26.136697
min     20.000000   501.000000   10.000000
25%     29.000000  1166.500000   29.250000
50%     40.000000  1756.000000   48.000000
75%     50.000000  2431.500000   74.000000
max     59.000000  2977.000000   99.000000

In [38]:
print("\ Archivo sin Na",
 dp_limpio.describe())

\ Archivo sin Na              edad       ventas    clientes
count  471.000000   471.000000  471.000000
mean    39.505308  1763.360934   51.668790
std     11.789983   710.263967   26.201037
min     20.000000   501.000000   10.000000
25%     29.000000  1185.000000   30.000000
50%     40.000000  1766.000000   48.000000
75%     50.000000  2430.000000   75.000000
max     59.000000  2974.000000   99.000000

## B.4 · Limpieza (opción B): rellenar por criterio
Más fino que borrar: rellenas **cada columna con la lógica que tiene sentido** — la edad con su
media, las ventas/clientes con 0 (porque un nulo ahí seguramente significa "no vendió").

In [39]:
### Rellenar valores vacios por variables segun diferentes criterios

dp["edad_limpio"]=dp["edad"].fillna(dp["edad"].mean())
dp["ventas_limpio"]=dp["ventas"].fillna(0)
dp["clientes_limpio"]=dp["clientes"].fillna(0)

In [40]:
# Mostrar filas con ventas NaN
dp[dp["ventas"].isna()]

,nombre,edad,departamento,ventas,clientes,edad_limpio,ventas_limpio,clientes_limpio
13,Marta,47.0,Marketing,NaN,22.0,47.000000,0.0,22.0
24,Elena,42.0,Marketing,NaN,17.0,42.000000,0.0,17.0
39,Carlos,36.0,Marketing,NaN,22.0,36.000000,0.0,22.0
197,Carlos,33.0,Soporte,NaN,41.0,33.000000,0.0,41.0
228,Raul,21.0,Ventas,NaN,51.0,21.000000,0.0,51.0
235,Lucia,35.0,Soporte,NaN,39.0,35.000000,0.0,39.0
243,Jorge,NaN,Ventas,NaN,82.0,39.497959,0.0,82.0
299,Elena,45.0,Marketing,NaN,19.0,45.000000,0.0,19.0
473,Lucia,34.0,Soporte,NaN,34.0,34.000000,0.0,34.0
486,Ana,46.0,Soporte,NaN,41.0,46.000000,0.0,41.0

## B.5 · Preguntas de negocio
La parte que de verdad importa: convertir la tabla en **respuestas**. Media de ventas, ventas por
departamento, el empleado top (`idxmax`), mayores de 30, qué departamento vende más…
Cada una de estas líneas es un `GROUP BY` / `WHERE` / `TOPN` que ya harías en SQL o Power BI.

In [41]:
# Calcular la media de las ventas

media_ventas = np.mean(dp["ventas"])
print(media_ventas)

1757.226530612245

In [42]:
## ventas por departamento

ventas_dep = dp.groupby('departamento')['ventas'].mean()
print(ventas_dep)

departamento
Marketing    1773.666667
Soporte      1811.937500
Ventas       1686.141975
Name: ventas, dtype: float64

In [43]:
# empleado con más venta

top = dp.loc[dp['ventas'].idxmax()]
print(top)

nombre                   Ana
edad                     NaN
departamento       Marketing
ventas                2977.0
clientes                67.0
edad_limpio        39.497959
ventas_limpio         2977.0
clientes_limpio         67.0
Name: 165, dtype: object

In [44]:
#Listado de los nombres de los empleados

listado = dp["nombre"]

print(listado)

0       Sofia
1      Carlos
2       Jorge
3       Lucia
4       Sofia
        ...
495       Ana
496     Sofia
497     Sofia
498     Elena
499     Marta
Name: nombre, Length: 500, dtype: object

In [45]:
#Empleados mayores de 30 años

print(dp[dp['edad']> 30])

     nombre  edad departamento  ventas  clientes  edad_limpio  ventas_limpio  \
0     Sofia  49.0       Ventas  2763.0      52.0         49.0         2763.0
1    Carlos  36.0       Ventas   502.0       NaN         36.0          502.0
2     Jorge  39.0    Marketing   659.0      32.0         39.0          659.0
3     Lucia  44.0    Marketing  1280.0      89.0         44.0         1280.0
4     Sofia  41.0      Soporte  1392.0      56.0         41.0         1392.0
..      ...   ...          ...     ...       ...          ...            ...
495     Ana  42.0      Soporte  1443.0      55.0         42.0         1443.0
496   Sofia  45.0       Ventas  2890.0      16.0         45.0         2890.0
497   Sofia  31.0       Ventas  1849.0      32.0         31.0         1849.0
498   Elena  45.0       Ventas  2911.0      84.0         45.0         2911.0
499   Marta  32.0    Marketing  1390.0      95.0         32.0         1390.0

     clientes_limpio
0               52.0
1                0.0
2               32.0
3               89.0
4               56.0
..               ...
495             55.0
496             16.0
497             32.0
498             84.0
499             95.0

[349 rows x 8 columns]

In [46]:
#Media de edad

print(dp['edad'].mean())

39.49795918367347

In [47]:
#Que departamento genera más ventas

ventas_dp = dp.groupby('departamento')['ventas'].sum()
print(ventas_dp)

departamento
Marketing    297976.0
Soporte      289910.0
Ventas       273155.0
Name: ventas, dtype: float64

In [48]:
ventas_dp = dp.groupby('departamento')['ventas'].sum()
print(ventas_dp.idxmax(), max(ventas_dp))

Marketing 297976.0

## B.6 · Columnas derivadas y el problema de dividir entre 0

Creas `ventas_x_cliente = ventas / clientes`. Pero si un empleado tiene **0 clientes**, dividir
entre 0 rompe el cálculo (da infinito o `NaN`). La solución elegante: `.replace(0, np.nan)` para
convertir esos ceros en nulos antes de dividir.

### Error común

Dividir entre una columna sin comprobar antes si contiene ceros. Es un error **clásico y muy
profesional** de detectar a tiempo — aquí se ve venir porque `clientes` puede legítimamente
valer 0, y `ventas / 0` no lanza una excepción en pandas (da `inf` o `NaN` silenciosamente), así
que si no lo compruebas, el error pasa desapercibido en vez de fallar de forma ruidosa.

### Aplicación profesional

`.replace(0, np.nan)` antes de dividir es el equivalente a un `DIVIDE()` de DAX, que ya
devuelve `BLANK()` en vez de error cuando el denominador es 0 — aquí lo haces explícito a mano.

In [49]:
#Nueva columna para ver las ventas por cliente = ventas/cliente

dp["ventas_x_cliente"]=dp["ventas"]/dp["clientes"]
display(dp)

,nombre,edad,departamento,ventas,clientes,edad_limpio,ventas_limpio,clientes_limpio,ventas_x_cliente
0,Sofia,49.0,Ventas,2763.0,52.0,49.0,2763.0,52.0,53.134615
1,Carlos,36.0,Ventas,502.0,NaN,36.0,502.0,0.0,NaN
2,Jorge,39.0,Marketing,659.0,32.0,39.0,659.0,32.0,20.593750
3,Lucia,44.0,Marketing,1280.0,89.0,44.0,1280.0,89.0,14.382022
4,Sofia,41.0,Soporte,1392.0,56.0,41.0,1392.0,56.0,24.857143
...,...,...,...,...,...,...,...,...,...
495,Ana,42.0,Soporte,1443.0,55.0,42.0,1443.0,55.0,26.236364
496,Sofia,45.0,Ventas,2890.0,16.0,45.0,2890.0,16.0,180.625000
497,Sofia,31.0,Ventas,1849.0,32.0,31.0,1849.0,32.0,57.781250
498,Elena,45.0,Ventas,2911.0,84.0,45.0,2911.0,84.0,34.654762
499,Marta,32.0,Marketing,1390.0,95.0,32.0,1390.0,95.0,14.631579

In [50]:
#Problema cuando hay valores 0 y nos rompe la división

dp["ventas_x_cliente"]=dp["ventas"]/dp["clientes"]
display(dp)

dp["ventas_x_cliente_d0"]=dp["ventas"]/dp["clientes"].replace(0,np.nan)
display(dp)

,nombre,edad,departamento,ventas,clientes,edad_limpio,ventas_limpio,clientes_limpio,ventas_x_cliente
0,Sofia,49.0,Ventas,2763.0,52.0,49.0,2763.0,52.0,53.134615
1,Carlos,36.0,Ventas,502.0,NaN,36.0,502.0,0.0,NaN
2,Jorge,39.0,Marketing,659.0,32.0,39.0,659.0,32.0,20.593750
3,Lucia,44.0,Marketing,1280.0,89.0,44.0,1280.0,89.0,14.382022
4,Sofia,41.0,Soporte,1392.0,56.0,41.0,1392.0,56.0,24.857143
...,...,...,...,...,...,...,...,...,...
495,Ana,42.0,Soporte,1443.0,55.0,42.0,1443.0,55.0,26.236364
496,Sofia,45.0,Ventas,2890.0,16.0,45.0,2890.0,16.0,180.625000
497,Sofia,31.0,Ventas,1849.0,32.0,31.0,1849.0,32.0,57.781250
498,Elena,45.0,Ventas,2911.0,84.0,45.0,2911.0,84.0,34.654762
499,Marta,32.0,Marketing,1390.0,95.0,32.0,1390.0,95.0,14.631579

,nombre,edad,departamento,ventas,clientes,edad_limpio,ventas_limpio,clientes_limpio,ventas_x_cliente,ventas_x_cliente_d0
0,Sofia,49.0,Ventas,2763.0,52.0,49.0,2763.0,52.0,53.134615,53.134615
1,Carlos,36.0,Ventas,502.0,NaN,36.0,502.0,0.0,NaN,NaN
2,Jorge,39.0,Marketing,659.0,32.0,39.0,659.0,32.0,20.593750,20.593750
3,Lucia,44.0,Marketing,1280.0,89.0,44.0,1280.0,89.0,14.382022,14.382022
4,Sofia,41.0,Soporte,1392.0,56.0,41.0,1392.0,56.0,24.857143,24.857143
...,...,...,...,...,...,...,...,...,...,...
495,Ana,42.0,Soporte,1443.0,55.0,42.0,1443.0,55.0,26.236364,26.236364
496,Sofia,45.0,Ventas,2890.0,16.0,45.0,2890.0,16.0,180.625000,180.625000
497,Sofia,31.0,Ventas,1849.0,32.0,31.0,1849.0,32.0,57.781250,57.781250
498,Elena,45.0,Ventas,2911.0,84.0,45.0,2911.0,84.0,34.654762,34.654762
499,Marta,32.0,Marketing,1390.0,95.0,32.0,1390.0,95.0,14.631579,14.631579

## B.7 · Percentiles

**Qué es:** un percentil parte los datos en cien trozos. El percentil 90 de ventas = el valor por debajo
del cual está el 90% de la gente; por encima queda el **10% que más vende**.

### Error común

Ojo al nombrar variables: aquí la variable se llama `p10` y `ventas_bajas`, pero al usar
`percentile(..., 90)` y filtrar `> p10` en realidad se está sacando el **10% más ALTO**, no el
más bajo. El cálculo es correcto; solo el nombre despista — un ejemplo real de por qué nombrar
variables según lo que *contienen* (no según de dónde vienen) evita confusiones a quien lea el
código después, incluido tú mismo dentro de un mes.

In [51]:

#Quiero sacar el percentil X de las ventas

p10= np.percentile(dp["ventas"].dropna(),90)
ventas_bajas=dp[dp["ventas"]>p10]
print(ventas_bajas)

     nombre  edad departamento  ventas  clientes  edad_limpio  ventas_limpio  \
0     Sofia  49.0       Ventas  2763.0      52.0    49.000000         2763.0
6     Marta  38.0    Marketing  2876.0      34.0    38.000000         2876.0
27    Marta  58.0       Ventas  2875.0      39.0    58.000000         2875.0
40    Elena  57.0    Marketing  2771.0      40.0    57.000000         2771.0
42     Raul  32.0       Ventas  2896.0      72.0    32.000000         2896.0
53     Luis  20.0       Ventas  2883.0      10.0    20.000000         2883.0
55   Carlos   NaN       Ventas  2900.0      54.0    39.497959         2900.0
62     Luis  38.0      Soporte  2969.0      35.0    38.000000         2969.0
70    Jorge  32.0    Marketing  2910.0      89.0    32.000000         2910.0
73    Lucia  47.0      Soporte  2903.0      46.0    47.000000         2903.0
88    Jorge  30.0      Soporte  2912.0      56.0    30.000000         2912.0
92    Lucia  38.0      Soporte  2961.0      90.0    38.000000         2961.0
99    Jorge  22.0    Marketing  2882.0      41.0    22.000000         2882.0
112   Lucia  27.0    Marketing  2948.0      27.0    27.000000         2948.0
116    Raul  27.0      Soporte  2757.0      50.0    27.000000         2757.0
117   Sofia  47.0      Soporte  2853.0      84.0    47.000000         2853.0
125  Carlos  39.0      Soporte  2928.0      41.0    39.000000         2928.0
136   Elena  29.0      Soporte  2944.0      58.0    29.000000         2944.0
147   Elena  41.0      Soporte  2850.0      59.0    41.000000         2850.0
165     Ana   NaN    Marketing  2977.0      67.0    39.497959         2977.0
174   Jorge  32.0    Marketing  2934.0      39.0    32.000000         2934.0
191   Sofia  49.0      Soporte  2933.0      30.0    49.000000         2933.0
215     Ana  36.0       Ventas  2948.0      35.0    36.000000         2948.0
227   Sofia  25.0    Marketing  2772.0      58.0    25.000000         2772.0
248  Carlos  40.0    Marketing  2770.0      11.0    40.000000         2770.0
259    Luis  53.0       Ventas  2930.0      42.0    53.000000         2930.0
281   Pedro  21.0    Marketing  2856.0      22.0    21.000000         2856.0
283   Marta  33.0      Soporte  2835.0      87.0    33.000000         2835.0
312   Elena  27.0       Ventas  2967.0      82.0    27.000000         2967.0
315    Raul  56.0      Soporte  2882.0      16.0    56.000000         2882.0
333   Sofia  22.0    Marketing  2881.0      23.0    22.000000         2881.0
336    Luis  56.0    Marketing  2840.0      14.0    56.000000         2840.0
338   Jorge  43.0    Marketing  2865.0      11.0    43.000000         2865.0
345   Jorge  23.0      Soporte  2778.0      67.0    23.000000         2778.0
359     Ana  38.0    Marketing  2834.0      69.0    38.000000         2834.0
370  Carlos  55.0       Ventas  2860.0      61.0    55.000000         2860.0
377    Luis  42.0      Soporte  2852.0      73.0    42.000000         2852.0
389   Sofia  30.0    Marketing  2881.0      30.0    30.000000         2881.0
404   Pedro  20.0      Soporte  2789.0      92.0    20.000000         2789.0
411   Elena  33.0      Soporte  2974.0      86.0    33.000000         2974.0
415   Lucia  56.0    Marketing  2931.0       NaN    56.000000         2931.0
432    Raul  42.0    Marketing  2858.0      67.0    42.000000         2858.0
434    Raul  52.0       Ventas  2974.0      14.0    52.000000         2974.0
449   Marta  48.0       Ventas  2908.0      77.0    48.000000         2908.0
462    Raul  41.0    Marketing  2944.0      25.0    41.000000         2944.0
478   Lucia  23.0    Marketing  2838.0      39.0    23.000000         2838.0
485   Marta  45.0      Soporte  2875.0      30.0    45.000000         2875.0
496   Sofia  45.0       Ventas  2890.0      16.0    45.000000         2890.0
498   Elena  45.0       Ventas  2911.0      84.0    45.000000         2911.0

     clientes_limpio  ventas_x_cliente  ventas_x_cliente_d0
0               52.0         53.134615            53.134615
6               34.0         84.588235            84.588235
27              39.0         73.717949            73.717949
40              40.0         69.275000            69.275000
42              72.0         40.222222            40.222222
53              10.0        288.300000           288.300000
55              54.0         53.703704            53.703704
62              35.0         84.828571            84.828571
70              89.0         32.696629            32.696629
73              46.0         63.108696            63.108696
88              56.0         52.000000            52.000000
92              90.0         32.900000            32.900000
99              41.0         70.292683            70.292683
112             27.0        109.185185           109.185185
116             50.0         55.140000            55.140000
117             84.0         33.964286            33.964286
125             41.0         71.414634            71.414634
136             58.0         50.758621            50.758621
147             59.0         48.305085            48.305085
165             67.0         44.432836            44.432836
174             39.0         75.230769            75.230769
191             30.0         97.766667            97.766667
215             35.0         84.228571            84.228571
227             58.0         47.793103            47.793103
248             11.0        251.818182           251.818182
259             42.0         69.761905            69.761905
281             22.0        129.818182           129.818182
283             87.0         32.586207            32.586207
312             82.0         36.182927            36.182927
315             16.0        180.125000           180.125000
333             23.0        125.260870           125.260870
336             14.0        202.857143           202.857143
338             11.0        260.454545           260.454545
345             67.0         41.462687            41.462687
359             69.0         41.072464            41.072464
370             61.0         46.885246            46.885246
377             73.0         39.068493            39.068493
389             30.0         96.033333            96.033333
404             92.0         30.315217            30.315217
411             86.0         34.581395            34.581395
415              0.0               NaN                  NaN
432             67.0         42.656716            42.656716
434             14.0        212.428571           212.428571
449             77.0         37.766234            37.766234
462             25.0        117.760000           117.760000
478             39.0         72.769231            72.769231
485             30.0         95.833333            95.833333
496             16.0        180.625000           180.625000
498             84.0         34.654762            34.654762

In [52]:
print(len(ventas_bajas))

49

In [53]:
ventas_bajas =dp[dp["ventas"]>510]
print(ventas_bajas)
print(len(ventas_bajas))

    nombre  edad departamento  ventas  clientes  edad_limpio  ventas_limpio  \
0    Sofia  49.0       Ventas  2763.0      52.0         49.0         2763.0
2    Jorge  39.0    Marketing   659.0      32.0         39.0          659.0
3    Lucia  44.0    Marketing  1280.0      89.0         44.0         1280.0
4    Sofia  41.0      Soporte  1392.0      56.0         41.0         1392.0
5     Raul  32.0      Soporte  2530.0      24.0         32.0         2530.0
..     ...   ...          ...     ...       ...          ...            ...
495    Ana  42.0      Soporte  1443.0      55.0         42.0         1443.0
496  Sofia  45.0       Ventas  2890.0      16.0         45.0         2890.0
497  Sofia  31.0       Ventas  1849.0      32.0         31.0         1849.0
498  Elena  45.0       Ventas  2911.0      84.0         45.0         2911.0
499  Marta  32.0    Marketing  1390.0      95.0         32.0         1390.0

     clientes_limpio  ventas_x_cliente  ventas_x_cliente_d0
0               52.0         53.134615            53.134615
2               32.0         20.593750            20.593750
3               89.0         14.382022            14.382022
4               56.0         24.857143            24.857143
5               24.0        105.416667           105.416667
..               ...               ...                  ...
495             55.0         26.236364            26.236364
496             16.0        180.625000           180.625000
497             32.0         57.781250            57.781250
498             84.0         34.654762            34.654762
499             95.0         14.631579            14.631579

[487 rows x 10 columns]
487

## B.8 · Correlación
La **correlación** mide si dos variables se mueven juntas (de −1 a +1). `df.corr()` te da la
**matriz de correlación** de todas las columnas numéricas.
> En el último ejemplo `["edad","clientes","edad"]` repite "edad" — la matriz sale igualmente,
> pero con una fila/columna duplicada. Curiosidad inofensiva.

**Puente:** en Power BI esto suele verse como un *scatter* con línea de tendencia; aquí lo tienes
en números, listo para decidir qué relaciones merece la pena visualizar (¡eso es el Módulo 4!).

In [54]:
print("\n ***** Matriz de correlación*****")
print(dp.corr(numeric_only=True))

 ***** Matriz de correlación*****
                         edad    ventas  clientes  edad_limpio  ventas_limpio  \
edad                 1.000000 -0.110360 -0.092106     1.000000      -0.097507
ventas              -0.110360  1.000000 -0.030393    -0.109266       1.000000
clientes            -0.092106 -0.030393  1.000000    -0.091178      -0.001711
edad_limpio          1.000000 -0.109266 -0.091178     1.000000      -0.096117
ventas_limpio       -0.097507  1.000000 -0.001711    -0.096117       1.000000
clientes_limpio     -0.092068 -0.011208  1.000000    -0.091208       0.012925
ventas_x_cliente    -0.004345  0.472306 -0.688305    -0.004323       0.472306
ventas_x_cliente_d0 -0.004345  0.472306 -0.688305    -0.004323       0.472306

                     clientes_limpio  ventas_x_cliente  ventas_x_cliente_d0
edad                       -0.092068         -0.004345            -0.004345
ventas                     -0.011208          0.472306             0.472306
clientes                    1.000000         -0.688305            -0.688305
edad_limpio                -0.091208         -0.004323            -0.004323
ventas_limpio               0.012925          0.472306             0.472306
clientes_limpio             1.000000         -0.688305            -0.688305
ventas_x_cliente           -0.688305          1.000000             1.000000
ventas_x_cliente_d0        -0.688305          1.000000             1.000000

In [55]:
variables=["edad","ventas"]
correlac=dp[variables].corr()
print(correlac)

           edad   ventas
edad    1.00000 -0.11036
ventas -0.11036  1.00000

In [56]:
variables=["edad","clientes"]
correlac=dp[variables].corr()
print(correlac)

              edad  clientes
edad      1.000000 -0.092106
clientes -0.092106  1.000000

In [57]:
variables=["edad","clientes", "edad"]
correlac=dp[variables].corr()
print(correlac)

              edad  clientes      edad
edad      1.000000 -0.092106  1.000000
clientes -0.092106  1.000000 -0.092106
edad      1.000000 -0.092106  1.000000

---
## Resumen del Módulo 3 — lo que ya dominas

```
Series (columna) vs DataFrame (tabla)
Cargar CSV con read_csv (rutas raw r"...")
EDA: head, tail, info, describe
Calidad de datos: isna().sum(), % de nulos
Limpieza: dropna (borrar) vs fillna (rellenar por criterio)
Columnas calculadas (vectorizadas) y filtros con máscaras
Estadística: mean, max, sort_values
groupby (= GROUP BY) → el corazón del análisis
Acceso a filas: iloc (posición) y loc (etiqueta/condición) + idxmax
División por cero con replace(0, np.nan)
Percentiles y matriz de correlación
```

### Próximo paso
**Módulo 4 — Visualización (Matplotlib + Seaborn).** Pasamos de los números a los **gráficos**:
la correlación que acabas de calcular se convierte en un mapa de calor, y las distribuciones en
histogramas. Es donde el análisis se vuelve **comunicación**.

> **Tres ideas clave:** (1) DataFrame = tabla de Excel en código. (2) `groupby` = `GROUP BY`.
> (3) Limpiar bien los datos es el 80% del trabajo real del analista.